import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Language = 'fr' | 'en' | 'es';

export interface Translations {
  [key: string]: string;
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<Language>('fr');
  public language$ = this.currentLanguage.asObservable();

  private translations: { [lang: string]: Translations } = {
    fr: {
      // Header & Navigation
      'settings': 'Paramètres',
      'settings.subtitle': 'Personnalisez votre app',
      'profile': 'Profil',
      'profile.subtitle': 'Gérez vos informations',
      'home': 'Accueil',
      'transactions': 'Transactions',
      'accounts': 'Comptes',
      
      // Settings - General
      'general': 'Général',
      'language': 'Langue',
      'language.description': 'Choisissez votre langue',
      'dark_mode': 'Mode sombre',
      'dark_mode.description': 'Activez le thème sombre',
      
      // Settings - Notifications
      'notifications': 'Notifications',
      'push_notifications': 'Notifications push',
      'push_notifications.description': 'Recevez des notifications',
      'email_notifications': 'Notifications email',
      'email_notifications.description': 'Recevez des emails',
      'messages': 'Messages',
      'messages.description': 'Notifications de messages',
      
      // Settings - Security
      'security': 'Sécurité & Confidentialité',
      'password': 'Mot de passe',
      'password.description': 'Modifiez votre mot de passe',
      'biometrics': 'Biométrie',
      'biometrics.description': 'Touch ID / Face ID',
      'two_factor': 'Vérification en 2 étapes',
      'two_factor.description': 'Sécurité renforcée',
      
      // Settings - Account
      'my_account': 'Mon compte',
      'profile.description': 'Gérez votre profil',
      'subscription': 'Abonnement',
      'subscription.description': 'Gérez votre abonnement',
      
      // Settings - Support
      'help_support': 'Aide & Support',
      'customer_support': 'Support client',
      'customer_support.description': 'Contactez-nous',
      'faq': 'FAQ',
      'faq.description': 'Questions fréquentes',
      'about': 'À propos',
      'about.description': 'Version 1.0.0',
      
      // Settings - Danger Zone
      'danger_zone': 'Zone dangereuse',
      'delete_account': 'Supprimer le compte',
      'delete_account.description': 'Cette action est irréversible',
      
      // Footer
      'all_rights_reserved': 'Tous droits réservés',
      
      // Profile Page
      'personal_info': 'Informations personnelles',
      'email': 'Email',
      'phone': 'Téléphone',
      'member_since': 'Membre depuis',
      'security_label': 'Sécurité',
      'protected_connection': 'Connexion protégée',
      'edit': 'Modifier',
      'edit.description': 'Mettre à jour vos infos',
      'photo': 'Photo',
      'photo.description': 'Changer votre avatar',
      'logout': 'Déconnexion',
      'logout.description': 'Quitter votre session',
      
      // Common
      'premium': 'Premium',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'back': 'Retour',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      
      // Tabs
      'tab.home': 'Accueil',
      'tab.accounts': 'Comptes',
      'tab.transactions': 'Transactions',
      'tab.activations': 'Activations',
      'tab.notifications': 'Notifications',
      'tab.settings': 'Paramètres',
      
      // Home Page (Tab1)
      'home.welcome': 'Bienvenue sur MoobilPay',
      'home.your_balance': 'Votre solde',
      'home.search': 'Rechercher un service...',
      'home.all': 'Tous',
      'home.streaming': 'Streaming',
      'home.music': 'Musique',
      'home.gaming': 'Gaming',
      'home.productivity': 'Productivité',
      'home.days_remaining': 'Jours restant',
      'home.days': 'jours',
      'home.plan': 'Plan',
      'home.month': 'mois',
      'home.resubscribe': 'Réabonner',
      'home.unsubscribe': 'Désabonner',
      'home.services_streaming': 'Services & Streaming',
      'home.services_subtitle': 'Gérez vos abonnements et accédez à vos services',
      'home.accounts': 'Comptes',
      'home.help': 'Aide',
      'home.news': 'Actus film',
      'home.share': 'Partager',
      'home.discover': 'Découvrir & Divertissement',
      'home.discover_subtitle': 'Explorez nos services de divertissement et plus encore',
      'home.cinema': 'Cinéma',
      'home.films_series': 'Films & séries',
      'home.games_consoles': 'Jeux & consoles',
      'home.shopping': 'Shopping',
      'home.online_shopping': 'Achats en ligne',
      'home.social': 'Social',
      'home.social_networks': 'Réseaux sociaux',
      'home.confirm_unsubscribe': 'Confirmer le désabonnement',
      'home.unsubscribe_warning': 'Vous êtes sur le point de perdre l\'accès à tous vos contenus Netflix Premium. Cette action est irréversible.',
      'home.shared_account': 'Compte partagé',
      'home.screens': 'écrans',
      'home.family': 'Famille',
      'home.profiles': 'profils',
      'home.unlimited_music': 'Musique illimitée',
      'home.active': 'Actif',
      'home.inactive': 'Inactif',
      
      // Transactions Page (Tab4)
      'transactions.title': 'Transactions',
      'transactions.subtitle': 'Historique de vos paiements',
      'transactions.all': 'Toutes',
      'transactions.income': 'Revenus',
      'transactions.expenses': 'Dépenses',
      'transactions.pending': 'En attente',
      'transactions.total_balance': 'Solde total',
      'transactions.this_month': 'Ce mois',
      'transactions.recent': 'Transactions récentes',
      'transactions.no_transactions': 'Aucune transaction',
      'transactions.date': 'Date',
      'transactions.amount': 'Montant',
      'transactions.status': 'Statut',
      'transactions.completed': 'Terminé',
      'transactions.failed': 'Echoué',
      'transactions.my_transactions': 'Mes Transactions',
      'transactions.total': 'Total',
      'transactions.overview': 'Aperçu',
      'transactions.spent': 'Dépensé',
      'transactions.savings': 'Économies',
      'transactions.filter': 'Filtrer',
      'transactions.monthly_subscription': 'Abonnement mensuel',
      'transactions.refund': 'Remboursement',
      'transactions.service_cancellation': 'Annulation service',
      
      // Activations Page
      'activations.title': 'Activations',
      'activations.subtitle': 'Gérez vos activations',
      'activations.active': 'Actives',
      'activations.pending': 'En attente',
      'activations.expired': 'Expirées',
      'activations.no_activations': 'Aucune activation',
      'activations.my_activations': 'Mes Activations',
      'activations.total': 'Total',
      'activations.overview': 'Aperçu',
      'activations.activated': 'Activées',
      'activations.history': 'Historique des activations',
      'activations.filter': 'Filtrer',
      'activations.loading': 'Chargement des activations...',
      'activations.will_appear_here': 'Vos activations apparaîtront ici',
      'activations.requested_on': 'Demandé le',
      'activations.start': 'Début',
      'activations.expires': 'Expire',
      'activations.status_activated': 'Activé',
      'activations.status_expired': 'Expiré',
      'activations.status_pending': 'En cours',
      
      // Notifications Page (Tab2)
      'notifications.title': 'Notifications',
      'notifications.subtitle': 'Restez informé',
      'notifications.today': 'Aujourd\'hui',
      'notifications.yesterday': 'Hier',
      'notifications.earlier': 'Plus tôt',
      'notifications.no_notifications': 'Aucune notification',
      'notifications.mark_all_read': 'Tout marquer comme lu',
      'notifications.premium': 'Premium',
      'notifications.verified': 'Vérifié',
      'notifications.edit_profile': 'Modifier le profil',
      'notifications.active_accounts': 'Comptes actifs',
      'notifications.referred_friends': 'Amis parrainés',
      'notifications.points_earned': 'Points gagnés',
      'notifications.quick_actions': 'Actions rapides',
      'notifications.quick_actions_desc': 'Accès direct à vos fonctionnalités',
      'notifications.statistics': 'Statistiques',
      'notifications.view_data': 'Voir vos données',
      'notifications.security': 'Sécurité',
      'notifications.protect_account': 'Protéger votre compte',
      'notifications.manage_alerts': 'Gérer vos alertes',
      'notifications.get_help': 'Obtenir de l\'aide',
      'notifications.account_management': 'Gestion du compte',
      'notifications.control_settings': 'Contrôlez tous vos paramètres',
      'notifications.my_subscriptions': 'Mes abonnements',
      'notifications.manage_streaming': 'Gérer vos comptes de streaming',
      'notifications.share_referral': 'Partage & Parrainage',
      'notifications.invite_friends': 'Inviter vos amis et gagner des points',
      'notifications.new': 'Nouveau',
      'notifications.payment_history': 'Historique de vos paiements',
      'notifications.logout': 'Se déconnecter',
      'notifications.logout_desc': 'Quitter votre session en toute sécurité',
      
      // Notification Component
      'notification.my_notifications': 'Mes Notifications',
      'notification.new_count': 'nouvelle(s)',
      'notification.up_to_date': 'À jour',
      'notification.total': 'Total',
      'notification.clear_all': 'Effacer tout',
      'notification.no_notifications': 'Aucune notification',
      'notification.no_notifications_desc': 'Vous êtes à jour ! Aucune nouvelle notification pour le moment.',
      'notification.delete_all': 'Supprimer toutes les notifications',
      'notification.delete_all_confirm': 'Voulez-vous vraiment supprimer toutes les notifications ?',
      'notification.delete': 'Supprimer',
      'notification.just_now': 'À l\'instant',
      'notification.min_ago': 'min',
      'notification.hours_ago': 'h',
      'notification.days_ago': 'jours',
      
      // Support Page
      'support.title': 'Centre d\'Aide',
      'support.subtitle': 'Nous sommes là pour vous accompagner',
      'support.contact_us': 'Nous Contacter',
      'support.live_chat': 'Chat en Direct',
      'support.email_us': 'Envoyez-nous un email',
      'support.call_us': 'Appelez-nous',
      'support.faq': 'FAQ',
      'support.guides': 'Guides',
      'support.help_center': 'Centre d\'Aide MoobilPay',
      'support.choose_help': 'Choisissez comment nous pouvons vous aider',
      'support.immediate_response': 'Réponse immédiate',
      'support.online': 'En ligne',
      'support.send_message': 'Envoyer un Message',
      'support.contact_form': 'Formulaire de contact',
      'support.response_2h': 'Réponse sous 2h',
      'support.phone': 'Téléphone',
      'support.phone_hours': 'Lun-Ven 8h-18h',
      'support.useful_resources': 'Ressources Utiles',
      'support.articles': 'articles',
      'support.videos': 'Vidéos',
      'support.tutorials': 'tutoriels',
      'support.community': 'Communauté',
      'support.members': 'membres',
      'support.faq_title': 'Questions Fréquentes',
      'support.faq_subtitle': 'Trouvez rapidement les réponses à vos questions',
      'support.guides_title': 'Guides d\'Utilisation',
      'support.guides_subtitle': 'Apprenez à utiliser MoobilPay étape par étape',
      'support.team_online': 'Notre équipe est en ligne pour vous aider',
      'support.bot_greeting': 'Bonjour ! Je suis l\'assistant MoobilPay. Comment puis-je vous aider aujourd\'hui ?',
      'support.now': 'Maintenant',
      'support.connection_issue': 'Problème de connexion',
      'support.add_account': 'Ajouter un compte',
      'support.billing_question': 'Question facturation',
      'support.type_message': 'Tapez votre message...',
      'support.request_type': 'Type de demande',
      'support.your_name': 'Votre nom',
      'support.your_email': 'Votre email',
      'support.subject': 'Sujet',
      'support.your_message': 'Votre message...',
      'support.ready_to_send': 'Prêt à envoyer',
      'next': 'Suivant',
      'send': 'Envoyer',
      
      // Account/Compte Page
      'account.my_accounts': 'Mes Comptes',
      'account.manage_streaming': 'Gérez vos comptes de streaming',
      'account.accounts': 'comptes',
      'account.total_accounts': 'Comptes total',
      'account.active': 'Actifs',
      'account.inactive': 'Inactifs',
      'account.your_streaming': 'Vos Comptes Streaming',
      'account.manage_accounts': 'Gérer mes comptes',
      'account.add_account': 'Ajouter un Compte',
      'account.connect_new': 'Connectez un nouveau service de streaming',
      
      // Share/Partage Page
      'sharing.title': 'Partage & Parrainage',
      'sharing.subtitle': 'Invitez vos amis et gagnez des récompenses',
      'sharing.referred_friends': 'Amis parrainés',
      'sharing.pending': 'En attente',
      'sharing.points_earned': 'Points gagnés',
      'sharing.your_code': 'Votre Code de Parrainage',
      'sharing.point_per_friend': '1 point par ami',
      'sharing.share_with_friends': 'Partager avec vos amis',
      'sharing.share_code': 'Partager mon code',
      'sharing.step1': 'Partagez votre code',
      'sharing.step2': 'Ami s\'inscrit',
      'sharing.step3': 'Vous gagnez 1 point',
      'sharing.qr_title': 'Code QR de Parrainage',
      'sharing.qr_description': 'Faites scanner ce code par vos amis pour qu\'ils s\'inscrivent directement avec votre code de parrainage',
      'sharing.download_qr': 'Télécharger le QR Code',
      
      // News/Actus Page
      'news.title': 'Actualités Cinéma',
      'news.subtitle': 'Découvrez les derniers films et séries',
      'news.featured': 'Film vedette',
      'news.new': 'Nouveau',
      'news.watch_trailer': 'Regarder la bande-annonce',
      'news.more_info': 'Plus d\'infos',
      'news.all': 'Tous',
      'news.trending': 'Tendances',
      'news.new_releases': 'Nouveautés',
      'news.trending_now': 'Tendances du moment',
      'news.trending_subtitle': 'Les films les plus populaires cette semaine',
      'news.new_releases_subtitle': 'Les derniers films ajoutés cette semaine',
      'news.notify_me': 'Me notifier',
    },
    en: {
      // Header & Navigation
      'settings': 'Settings',
      'settings.subtitle': 'Customize your app',
      'profile': 'Profile',
      'profile.subtitle': 'Manage your information',
      'home': 'Home',
      'transactions': 'Transactions',
      'accounts': 'Accounts',
      
      // Settings - General
      'general': 'General',
      'language': 'Language',
      'language.description': 'Choose your language',
      'dark_mode': 'Dark mode',
      'dark_mode.description': 'Enable dark theme',
      
      // Settings - Notifications
      'notifications': 'Notifications',
      'push_notifications': 'Push notifications',
      'push_notifications.description': 'Receive notifications',
      'email_notifications': 'Email notifications',
      'email_notifications.description': 'Receive emails',
      'messages': 'Messages',
      'messages.description': 'Message notifications',
      
      // Settings - Security
      'security': 'Security & Privacy',
      'password': 'Password',
      'password.description': 'Change your password',
      'biometrics': 'Biometrics',
      'biometrics.description': 'Touch ID / Face ID',
      'two_factor': '2-Step Verification',
      'two_factor.description': 'Enhanced security',
      
      // Settings - Account
      'my_account': 'My account',
      'profile.description': 'Manage your profile',
      'subscription': 'Subscription',
      'subscription.description': 'Manage your subscription',
      
      // Settings - Support
      'help_support': 'Help & Support',
      'customer_support': 'Customer support',
      'customer_support.description': 'Contact us',
      'faq': 'FAQ',
      'faq.description': 'Frequently asked questions',
      'about': 'About',
      'about.description': 'Version 1.0.0',
      
      // Settings - Danger Zone
      'danger_zone': 'Danger zone',
      'delete_account': 'Delete account',
      'delete_account.description': 'This action is irreversible',
      
      // Footer
      'all_rights_reserved': 'All rights reserved',
      
      // Profile Page
      'personal_info': 'Personal information',
      'email': 'Email',
      'phone': 'Phone',
      'member_since': 'Member since',
      'security_label': 'Security',
      'protected_connection': 'Protected connection',
      'edit': 'Edit',
      'edit.description': 'Update your info',
      'photo': 'Photo',
      'photo.description': 'Change your avatar',
      'logout': 'Logout',
      'logout.description': 'Sign out of your session',
      
      // Common
      'premium': 'Premium',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'back': 'Back',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      
      // Tabs
      'tab.home': 'Home',
      'tab.accounts': 'Accounts',
      'tab.transactions': 'Transactions',
      'tab.activations': 'Activations',
      'tab.notifications': 'Notifications',
      'tab.settings': 'Settings',
      
      // Home Page (Tab1)
      'home.welcome': 'Welcome to MoobilPay',
      'home.your_balance': 'Your balance',
      'home.search': 'Search for a service...',
      'home.all': 'All',
      'home.streaming': 'Streaming',
      'home.music': 'Music',
      'home.gaming': 'Gaming',
      'home.productivity': 'Productivity',
      'home.days_remaining': 'Days remaining',
      'home.days': 'days',
      'home.plan': 'Plan',
      'home.month': 'month',
      'home.resubscribe': 'Resubscribe',
      'home.unsubscribe': 'Unsubscribe',
      'home.services_streaming': 'Services & Streaming',
      'home.services_subtitle': 'Manage your subscriptions and access your services',
      'home.accounts': 'Accounts',
      'home.help': 'Help',
      'home.news': 'Film news',
      'home.share': 'Share',
      'home.discover': 'Discover & Entertainment',
      'home.discover_subtitle': 'Explore our entertainment services and more',
      'home.cinema': 'Cinema',
      'home.films_series': 'Films & series',
      'home.games_consoles': 'Games & consoles',
      'home.shopping': 'Shopping',
      'home.online_shopping': 'Online shopping',
      'home.social': 'Social',
      'home.social_networks': 'Social networks',
      'home.confirm_unsubscribe': 'Confirm unsubscription',
      'home.unsubscribe_warning': 'You are about to lose access to all your Netflix Premium content. This action is irreversible.',
      'home.shared_account': 'Shared account',
      'home.screens': 'screens',
      'home.family': 'Family',
      'home.profiles': 'profiles',
      'home.unlimited_music': 'Unlimited music',
      'home.active': 'Active',
      'home.inactive': 'Inactive',
      
      // Transactions Page (Tab4)
      'transactions.title': 'Transactions',
      'transactions.subtitle': 'Your payment history',
      'transactions.all': 'All',
      'transactions.income': 'Income',
      'transactions.expenses': 'Expenses',
      'transactions.pending': 'Pending',
      'transactions.total_balance': 'Total balance',
      'transactions.this_month': 'This month',
      'transactions.recent': 'Recent transactions',
      'transactions.no_transactions': 'No transactions',
      'transactions.date': 'Date',
      'transactions.amount': 'Amount',
      'transactions.status': 'Status',
      'transactions.completed': 'Completed',
      'transactions.failed': 'Failed',
      'transactions.my_transactions': 'My Transactions',
      'transactions.total': 'Total',
      'transactions.overview': 'Overview',
      'transactions.spent': 'Spent',
      'transactions.savings': 'Savings',
      'transactions.filter': 'Filter',
      'transactions.monthly_subscription': 'Monthly subscription',
      'transactions.refund': 'Refund',
      'transactions.service_cancellation': 'Service cancellation',
      
      // Activations Page
      'activations.title': 'Activations',
      'activations.subtitle': 'Manage your activations',
      'activations.active': 'Active',
      'activations.pending': 'Pending',
      'activations.expired': 'Expired',
      'activations.no_activations': 'No activations',
      'activations.my_activations': 'My Activations',
      'activations.total': 'Total',
      'activations.overview': 'Overview',
      'activations.activated': 'Activated',
      'activations.history': 'Activation history',
      'activations.filter': 'Filter',
      'activations.loading': 'Loading activations...',
      'activations.will_appear_here': 'Your activations will appear here',
      'activations.requested_on': 'Requested on',
      'activations.start': 'Start',
      'activations.expires': 'Expires',
      'activations.status_activated': 'Activated',
      'activations.status_expired': 'Expired',
      'activations.status_pending': 'Pending',
      
      // Notifications Page (Tab2)
      'notifications.title': 'Notifications',
      'notifications.subtitle': 'Stay informed',
      'notifications.today': 'Today',
      'notifications.yesterday': 'Yesterday',
      'notifications.earlier': 'Earlier',
      'notifications.no_notifications': 'No notifications',
      'notifications.mark_all_read': 'Mark all as read',
      'notifications.premium': 'Premium',
      'notifications.verified': 'Verified',
      'notifications.edit_profile': 'Edit profile',
      'notifications.active_accounts': 'Active accounts',
      'notifications.referred_friends': 'Referred friends',
      'notifications.points_earned': 'Points earned',
      'notifications.quick_actions': 'Quick actions',
      'notifications.quick_actions_desc': 'Direct access to your features',
      'notifications.statistics': 'Statistics',
      'notifications.view_data': 'View your data',
      'notifications.security': 'Security',
      'notifications.protect_account': 'Protect your account',
      'notifications.manage_alerts': 'Manage your alerts',
      'notifications.get_help': 'Get help',
      'notifications.account_management': 'Account management',
      'notifications.control_settings': 'Control all your settings',
      'notifications.my_subscriptions': 'My subscriptions',
      'notifications.manage_streaming': 'Manage your streaming accounts',
      'notifications.share_referral': 'Share & Referral',
      'notifications.invite_friends': 'Invite friends and earn points',
      'notifications.new': 'New',
      'notifications.payment_history': 'Payment history',
      'notifications.logout': 'Logout',
      'notifications.logout_desc': 'Sign out safely',
      
      // Notification Component
      'notification.my_notifications': 'My Notifications',
      'notification.new_count': 'new',
      'notification.up_to_date': 'Up to date',
      'notification.total': 'Total',
      'notification.clear_all': 'Clear all',
      'notification.no_notifications': 'No notifications',
      'notification.no_notifications_desc': 'You are up to date! No new notifications at the moment.',
      'notification.delete_all': 'Delete all notifications',
      'notification.delete_all_confirm': 'Are you sure you want to delete all notifications?',
      'notification.delete': 'Delete',
      'notification.just_now': 'Just now',
      'notification.min_ago': 'min ago',
      'notification.hours_ago': 'h ago',
      'notification.days_ago': 'days ago',
      
      // Support Page
      'support.title': 'Help Center',
      'support.subtitle': 'We are here to help you',
      'support.contact_us': 'Contact Us',
      'support.live_chat': 'Live Chat',
      'support.email_us': 'Email us',
      'support.call_us': 'Call us',
      'support.faq': 'FAQ',
      'support.guides': 'Guides',
      'support.help_center': 'MoobilPay Help Center',
      'support.choose_help': 'Choose how we can help you',
      'support.immediate_response': 'Immediate response',
      'support.online': 'Online',
      'support.send_message': 'Send a Message',
      'support.contact_form': 'Contact form',
      'support.response_2h': 'Response within 2h',
      'support.phone': 'Phone',
      'support.phone_hours': 'Mon-Fri 8am-6pm',
      'support.useful_resources': 'Useful Resources',
      'support.articles': 'articles',
      'support.videos': 'Videos',
      'support.tutorials': 'tutorials',
      'support.community': 'Community',
      'support.members': 'members',
      'support.faq_title': 'Frequently Asked Questions',
      'support.faq_subtitle': 'Quickly find answers to your questions',
      'support.guides_title': 'User Guides',
      'support.guides_subtitle': 'Learn to use MoobilPay step by step',
      'support.team_online': 'Our team is online to help you',
      'support.bot_greeting': 'Hello! I\'m the MoobilPay assistant. How can I help you today?',
      'support.now': 'Now',
      'support.connection_issue': 'Connection issue',
      'support.add_account': 'Add account',
      'support.billing_question': 'Billing question',
      'support.type_message': 'Type your message...',
      'support.request_type': 'Request type',
      'support.your_name': 'Your name',
      'support.your_email': 'Your email',
      'support.subject': 'Subject',
      'support.your_message': 'Your message...',
      'support.ready_to_send': 'Ready to send',
      'next': 'Next',
      'send': 'Send',
      
      // Account/Compte Page
      'account.my_accounts': 'My Accounts',
      'account.manage_streaming': 'Manage your streaming accounts',
      'account.accounts': 'accounts',
      'account.total_accounts': 'Total accounts',
      'account.active': 'Active',
      'account.inactive': 'Inactive',
      'account.your_streaming': 'Your Streaming Accounts',
      'account.manage_accounts': 'Manage my accounts',
      'account.add_account': 'Add Account',
      'account.connect_new': 'Connect a new streaming service',
      
      // Share/Partage Page
      'sharing.title': 'Share & Referral',
      'sharing.subtitle': 'Invite your friends and earn rewards',
      'sharing.referred_friends': 'Referred friends',
      'sharing.pending': 'Pending',
      'sharing.points_earned': 'Points earned',
      'sharing.your_code': 'Your Referral Code',
      'sharing.point_per_friend': '1 point per friend',
      'sharing.share_with_friends': 'Share with your friends',
      'sharing.share_code': 'Share my code',
      'sharing.step1': 'Share your code',
      'sharing.step2': 'Friend signs up',
      'sharing.step3': 'You earn 1 point',
      'sharing.qr_title': 'Referral QR Code',
      'sharing.qr_description': 'Have your friends scan this code to sign up directly with your referral code',
      'sharing.download_qr': 'Download QR Code',
      
      // News/Actus Page
      'news.title': 'Cinema News',
      'news.subtitle': 'Discover the latest films and series',
      'news.featured': 'Featured',
      'news.new': 'New',
      'news.watch_trailer': 'Watch trailer',
      'news.more_info': 'More info',
      'news.all': 'All',
      'news.trending': 'Trending',
      'news.new_releases': 'New releases',
      'news.trending_now': 'Trending now',
      'news.trending_subtitle': 'Most popular movies this week',
      'news.new_releases_subtitle': 'Latest movies added this week',
      'news.notify_me': 'Notify me',
    },
    es: {
      // Header & Navigation
      'settings': 'Configuración',
      'settings.subtitle': 'Personaliza tu app',
      'profile': 'Perfil',
      'profile.subtitle': 'Gestiona tu información',
      'home': 'Inicio',
      'transactions': 'Transacciones',
      'accounts': 'Cuentas',
      
      // Settings - General
      'general': 'General',
      'language': 'Idioma',
      'language.description': 'Elige tu idioma',
      'dark_mode': 'Modo oscuro',
      'dark_mode.description': 'Activar tema oscuro',
      
      // Settings - Notifications
      'notifications': 'Notificaciones',
      'push_notifications': 'Notificaciones push',
      'push_notifications.description': 'Recibir notificaciones',
      'email_notifications': 'Notificaciones por email',
      'email_notifications.description': 'Recibir emails',
      'messages': 'Mensajes',
      'messages.description': 'Notificaciones de mensajes',
      
      // Settings - Security
      'security': 'Seguridad y Privacidad',
      'password': 'Contraseña',
      'password.description': 'Cambia tu contraseña',
      'biometrics': 'Biometría',
      'biometrics.description': 'Touch ID / Face ID',
      'two_factor': 'Verificación en 2 pasos',
      'two_factor.description': 'Seguridad mejorada',
      
      // Settings - Account
      'my_account': 'Mi cuenta',
      'profile.description': 'Gestiona tu perfil',
      'subscription': 'Suscripción',
      'subscription.description': 'Gestiona tu suscripción',
      
      // Settings - Support
      'help_support': 'Ayuda y Soporte',
      'customer_support': 'Soporte al cliente',
      'customer_support.description': 'Contáctanos',
      'faq': 'FAQ',
      'faq.description': 'Preguntas frecuentes',
      'about': 'Acerca de',
      'about.description': 'Versión 1.0.0',
      
      // Settings - Danger Zone
      'danger_zone': 'Zona peligrosa',
      'delete_account': 'Eliminar cuenta',
      'delete_account.description': 'Esta acción es irreversible',
      
      // Footer
      'all_rights_reserved': 'Todos los derechos reservados',
      
      // Profile Page
      'personal_info': 'Información personal',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'member_since': 'Miembro desde',
      'security_label': 'Seguridad',
      'protected_connection': 'Conexión protegida',
      'edit': 'Editar',
      'edit.description': 'Actualizar tu información',
      'photo': 'Foto',
      'photo.description': 'Cambiar tu avatar',
      'logout': 'Cerrar sesión',
      'logout.description': 'Salir de tu sesión',
      
      // Common
      'premium': 'Premium',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'back': 'Volver',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      
      // Tabs
      'tab.home': 'Inicio',
      'tab.accounts': 'Cuentas',
      'tab.transactions': 'Transacciones',
      'tab.activations': 'Activaciones',
      'tab.notifications': 'Notificaciones',
      'tab.settings': 'Configuración',
      
      // Home Page (Tab1)
      'home.welcome': 'Bienvenido a MoobilPay',
      'home.your_balance': 'Tu saldo',
      'home.search': 'Buscar un servicio...',
      'home.all': 'Todos',
      'home.streaming': 'Streaming',
      'home.music': 'Música',
      'home.gaming': 'Gaming',
      'home.productivity': 'Productividad',
      'home.days_remaining': 'Días restantes',
      'home.days': 'días',
      'home.plan': 'Plan',
      'home.month': 'mes',
      'home.resubscribe': 'Resuscribir',
      'home.unsubscribe': 'Desuscribir',
      'home.services_streaming': 'Servicios & Streaming',
      'home.services_subtitle': 'Gestiona tus suscripciones y accede a tus servicios',
      'home.accounts': 'Cuentas',
      'home.help': 'Ayuda',
      'home.news': 'Noticias cine',
      'home.share': 'Compartir',
      'home.discover': 'Descubrir & Entretenimiento',
      'home.discover_subtitle': 'Explora nuestros servicios de entretenimiento y más',
      'home.cinema': 'Cine',
      'home.films_series': 'Películas & series',
      'home.games_consoles': 'Juegos & consolas',
      'home.shopping': 'Compras',
      'home.online_shopping': 'Compras en línea',
      'home.social': 'Social',
      'home.social_networks': 'Redes sociales',
      'home.confirm_unsubscribe': 'Confirmar cancelación',
      'home.unsubscribe_warning': 'Estás a punto de perder el acceso a todo tu contenido de Netflix Premium. Esta acción es irreversible.',
      'home.shared_account': 'Cuenta compartida',
      'home.screens': 'pantallas',
      'home.family': 'Familia',
      'home.profiles': 'perfiles',
      'home.unlimited_music': 'Música ilimitada',
      'home.active': 'Activo',
      'home.inactive': 'Inactivo',
      
      // Transactions Page (Tab4)
      'transactions.title': 'Transacciones',
      'transactions.subtitle': 'Historial de pagos',
      'transactions.all': 'Todas',
      'transactions.income': 'Ingresos',
      'transactions.expenses': 'Gastos',
      'transactions.pending': 'Pendientes',
      'transactions.total_balance': 'Saldo total',
      'transactions.this_month': 'Este mes',
      'transactions.recent': 'Transacciones recientes',
      'transactions.no_transactions': 'Sin transacciones',
      'transactions.date': 'Fecha',
      'transactions.amount': 'Monto',
      'transactions.status': 'Estado',
      'transactions.completed': 'Completado',
      'transactions.failed': 'Fallido',
      'transactions.my_transactions': 'Mis Transacciones',
      'transactions.total': 'Total',
      'transactions.overview': 'Resumen',
      'transactions.spent': 'Gastado',
      'transactions.savings': 'Ahorros',
      'transactions.filter': 'Filtrar',
      'transactions.monthly_subscription': 'Suscripción mensual',
      'transactions.refund': 'Reembolso',
      'transactions.service_cancellation': 'Cancelación servicio',
      
      // Activations Page
      'activations.title': 'Activaciones',
      'activations.subtitle': 'Gestiona tus activaciones',
      'activations.active': 'Activas',
      'activations.pending': 'Pendientes',
      'activations.expired': 'Expiradas',
      'activations.no_activations': 'Sin activaciones',
      'activations.my_activations': 'Mis Activaciones',
      'activations.total': 'Total',
      'activations.overview': 'Resumen',
      'activations.activated': 'Activadas',
      'activations.history': 'Historial de activaciones',
      'activations.filter': 'Filtrar',
      'activations.loading': 'Cargando activaciones...',
      'activations.will_appear_here': 'Tus activaciones aparecerán aquí',
      'activations.requested_on': 'Solicitado el',
      'activations.start': 'Inicio',
      'activations.expires': 'Expira',
      'activations.status_activated': 'Activado',
      'activations.status_expired': 'Expirado',
      'activations.status_pending': 'Pendiente',
      
      // Notifications Page (Tab2)
      'notifications.title': 'Notificaciones',
      'notifications.subtitle': 'Manténte informado',
      'notifications.today': 'Hoy',
      'notifications.yesterday': 'Ayer',
      'notifications.earlier': 'Antes',
      'notifications.no_notifications': 'Sin notificaciones',
      'notifications.mark_all_read': 'Marcar todo como leído',
      'notifications.premium': 'Premium',
      'notifications.verified': 'Verificado',
      'notifications.edit_profile': 'Editar perfil',
      'notifications.active_accounts': 'Cuentas activas',
      'notifications.referred_friends': 'Amigos referidos',
      'notifications.points_earned': 'Puntos ganados',
      'notifications.quick_actions': 'Acciones rápidas',
      'notifications.quick_actions_desc': 'Acceso directo a tus funciones',
      'notifications.statistics': 'Estadísticas',
      'notifications.view_data': 'Ver tus datos',
      'notifications.security': 'Seguridad',
      'notifications.protect_account': 'Proteger tu cuenta',
      'notifications.manage_alerts': 'Gestionar tus alertas',
      'notifications.get_help': 'Obtener ayuda',
      'notifications.account_management': 'Gestión de cuenta',
      'notifications.control_settings': 'Controla todos tus ajustes',
      'notifications.my_subscriptions': 'Mis suscripciones',
      'notifications.manage_streaming': 'Gestiona tus cuentas de streaming',
      'notifications.share_referral': 'Compartir & Referidos',
      'notifications.invite_friends': 'Invita amigos y gana puntos',
      'notifications.new': 'Nuevo',
      'notifications.payment_history': 'Historial de pagos',
      'notifications.logout': 'Cerrar sesión',
      'notifications.logout_desc': 'Salir de forma segura',
      
      // Notification Component
      'notification.my_notifications': 'Mis Notificaciones',
      'notification.new_count': 'nueva(s)',
      'notification.up_to_date': 'Al día',
      'notification.total': 'Total',
      'notification.clear_all': 'Borrar todo',
      'notification.no_notifications': 'Sin notificaciones',
      'notification.no_notifications_desc': '¡Estás al día! No hay nuevas notificaciones por el momento.',
      'notification.delete_all': 'Eliminar todas las notificaciones',
      'notification.delete_all_confirm': '¿Estás seguro de que quieres eliminar todas las notificaciones?',
      'notification.delete': 'Eliminar',
      'notification.just_now': 'Ahora mismo',
      'notification.min_ago': 'min',
      'notification.hours_ago': 'h',
      'notification.days_ago': 'días',
      
      // Support Page
      'support.title': 'Centro de Ayuda',
      'support.subtitle': 'Estamos aquí para ayudarte',
      'support.contact_us': 'Contáctanos',
      'support.live_chat': 'Chat en Vivo',
      'support.email_us': 'Envíanos un correo',
      'support.call_us': 'Llámanos',
      'support.faq': 'FAQ',
      'support.guides': 'Guías',
      'support.help_center': 'Centro de Ayuda MoobilPay',
      'support.choose_help': 'Elige cómo podemos ayudarte',
      'support.immediate_response': 'Respuesta inmediata',
      'support.online': 'En línea',
      'support.send_message': 'Enviar un Mensaje',
      'support.contact_form': 'Formulario de contacto',
      'support.response_2h': 'Respuesta en 2h',
      'support.phone': 'Teléfono',
      'support.phone_hours': 'Lun-Vie 8am-6pm',
      'support.useful_resources': 'Recursos Útiles',
      'support.articles': 'artículos',
      'support.videos': 'Videos',
      'support.tutorials': 'tutoriales',
      'support.community': 'Comunidad',
      'support.members': 'miembros',
      'support.faq_title': 'Preguntas Frecuentes',
      'support.faq_subtitle': 'Encuentra rápidamente las respuestas a tus preguntas',
      'support.guides_title': 'Guías de Uso',
      'support.guides_subtitle': 'Aprende a usar MoobilPay paso a paso',
      'support.team_online': 'Nuestro equipo está en línea para ayudarte',
      'support.bot_greeting': '¡Hola! Soy el asistente MoobilPay. ¿Cómo puedo ayudarte hoy?',
      'support.now': 'Ahora',
      'support.connection_issue': 'Problema de conexión',
      'support.add_account': 'Añadir cuenta',
      'support.billing_question': 'Pregunta de facturación',
      'support.type_message': 'Escribe tu mensaje...',
      'support.request_type': 'Tipo de solicitud',
      'support.your_name': 'Tu nombre',
      'support.your_email': 'Tu correo',
      'support.subject': 'Asunto',
      'support.your_message': 'Tu mensaje...',
      'support.ready_to_send': 'Listo para enviar',
      'next': 'Siguiente',
      'send': 'Enviar',
      
      // Account/Compte Page
      'account.my_accounts': 'Mis Cuentas',
      'account.manage_streaming': 'Gestiona tus cuentas de streaming',
      'account.accounts': 'cuentas',
      'account.total_accounts': 'Cuentas totales',
      'account.active': 'Activas',
      'account.inactive': 'Inactivas',
      'account.your_streaming': 'Tus Cuentas Streaming',
      'account.manage_accounts': 'Gestionar mis cuentas',
      'account.add_account': 'Añadir Cuenta',
      'account.connect_new': 'Conecta un nuevo servicio de streaming',
      
      // Share/Partage Page
      'sharing.title': 'Compartir & Referidos',
      'sharing.subtitle': 'Invita a tus amigos y gana recompensas',
      'sharing.referred_friends': 'Amigos referidos',
      'sharing.pending': 'Pendiente',
      'sharing.points_earned': 'Puntos ganados',
      'sharing.your_code': 'Tu Código de Referido',
      'sharing.point_per_friend': '1 punto por amigo',
      'sharing.share_with_friends': 'Compartir con tus amigos',
      'sharing.share_code': 'Compartir mi código',
      'sharing.step1': 'Comparte tu código',
      'sharing.step2': 'Amigo se registra',
      'sharing.step3': 'Ganas 1 punto',
      'sharing.qr_title': 'Código QR de Referido',
      'sharing.qr_description': 'Haz que tus amigos escaneen este código para registrarse directamente con tu código de referido',
      'sharing.download_qr': 'Descargar Código QR',
      
      // News/Actus Page
      'news.title': 'Noticias de Cine',
      'news.subtitle': 'Descubre las últimas películas y series',
      'news.featured': 'Destacado',
      'news.new': 'Nuevo',
      'news.watch_trailer': 'Ver tráiler',
      'news.more_info': 'Más info',
      'news.all': 'Todos',
      'news.trending': 'Tendencias',
      'news.new_releases': 'Novedades',
      'news.trending_now': 'Tendencias actuales',
      'news.trending_subtitle': 'Las películas más populares esta semana',
      'news.new_releases_subtitle': 'Últimas películas añadidas esta semana',
      'news.notify_me': 'Notificarme',
    }
  };

  constructor() {
    const savedLanguage = (localStorage.getItem('moobilpay-language') as Language) || (localStorage.getItem('mobilpay-language') as Language);
    if (savedLanguage && this.translations[savedLanguage]) {
      // Migrer l'ancienne clé si nécessaire
      if (!localStorage.getItem('moobilpay-language') && localStorage.getItem('mobilpay-language')) {
        localStorage.setItem('moobilpay-language', savedLanguage);
      }
      this.currentLanguage.next(savedLanguage);
    }
  }

  setLanguage(lang: Language): void {
    if (this.translations[lang]) {
      this.currentLanguage.next(lang);
      localStorage.setItem('moobilpay-language', lang);
      console.log(`Langue changée vers: ${lang}`);
    }
  }

  getCurrentLanguage(): Language {
    return this.currentLanguage.value;
  }

  translate(key: string): string {
    const lang = this.currentLanguage.value;
    return this.translations[lang]?.[key] || this.translations['fr']?.[key] || key;
  }

  t(key: string): string {
    return this.translate(key);
  }

  getLanguageName(lang: Language): string {
    const names: { [key: string]: string } = {
      'fr': '🇫🇷 Français',
      'en': '🇬🇧 English',
      'es': '🇪🇸 Español'
    };
    return names[lang] || lang;
  }

  getAvailableLanguages(): { code: Language; name: string }[] {
    return [
      { code: 'fr', name: '🇫🇷 Français' },
      { code: 'en', name: '🇬🇧 English' },
      { code: 'es', name: '🇪🇸 Español' }
    ];
  }
}
